### ISSUE TITLE
uristmaps.jar exception: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by BlueNalgene** [dominiks/uristmapsj#2]
Running uristmaps.jar or uristmaps.sh in Linux gives an exception in the threads.  Debug output is:

```

00:00  INFO: Uristmaps 0.3.2
00:00  INFO: Enabled Debug Logging
00:01  INFO: Starting full build
00:01 DEBUG: [TaskExecutor] Starting: BmpConvertTask
00:01 DEBUG: [BmpConverter] Started
00:01 DEBUG: [TaskExecutor] Completed: BmpConvertTask
00:01 DEBUG: [TaskExecutor] Starting: DistResources
00:01  INFO: [FileCopier] Copying static resources to output.
00:02 DEBUG: [TaskExecutor] Completed: DistResources
00:02 DEBUG: [TaskExecutor] Starting: GroupStructures
00:02 DEBUG: [StructureGroups] Reading groupMap from exported files.
00:02 DEBUG: [StructureInfo] Loading
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simontuffs.onejar.Boot.run(Boot.java:342)
        at com.simontuffs.onejar.Boot.main(Boot.java:168)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.uristmaps.StructureInfo.updateStructureConnections(StructureInfo.java:112)
        at org.uristmaps.StructureInfo.load(StructureInfo.java:101)
        at org.uristmaps.StructureInfo.getData(StructureInfo.java:176)
        at org.uristmaps.StructureGroups.load(StructureGroups.java:76)
        at org.uristmaps.Uristmaps.lambda$main$12(Uristmaps.java:133)
        at org.uristmaps.Uristmaps$$Lambda$17/19414242.run(Unknown Source)
        at org.uristmaps.tasks.AdhocTask.work(AdhocTask.java:47)
        at org.uristmaps.tasks.TaskExecutor.execTask(TaskExecutor.java:170)
        at org.uristmaps.tasks.TaskExecutor.execTask(TaskExecutor.java:159)
        at org.uristmaps.tasks.TaskExecutor.execTask(TaskExecutor.java:159)
        at org.uristmaps.tasks.TaskExecutor.execTask(TaskExecutor.java:159)
        at org.uristmaps.tasks.TaskExecutor.exec(TaskExecutor.java:84)
        at org.uristmaps.Uristmaps.main(Uristmaps.java:163)
        ... 6 more

```

Running the .jar file directly with -verbose:class enabled, the last few lines of relevant output are:

```

[Loaded java.awt.image.BufferedImage$1 from /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar]
[Loaded sun.awt.image.IntegerComponentRaster from /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar]
[Loaded java.awt.image.IndexColorModel from /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar]
[Loaded sun.awt.image.ShortComponentRaster from /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar]
[Loaded com.sun.imageio.plugins.common.ReaderUtil from /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar]
[Loaded java.io.RandomAccessFile$1 from /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar]
[Unloading class java.lang.invoke.LambdaForm$BMH/18707146 0xa46ff818]
[Unloading class java.lang.invoke.LambdaForm$BMH/21122690 0xa46fee18]
[Unloading class java.lang.invoke.LambdaForm$BMH/24137948 0xa46fda18]
[Unloading class java.lang.invoke.LambdaForm$BMH/15096457 0xa46f0018]
[Unloading class java.lang.invoke.LambdaForm$BMH/33078119 0xa46dc018]
Exception in thread "main" [Loaded java.lang.Throwable$PrintStreamOrWriter from /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar]
[Loaded java.lang.Throwable$WrappedPrintStream from /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar]
[Loaded java.util.IdentityHashMap$KeySet from /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar]
java.lang.reflect.InvocationTargetException
```

before running java shutdown routines.

This issue may be related to #1 , but I cannot tell at this time.

**Comment by dominiks** [comment]
Please try version 0.3.3 and see if the issue persists.

**Comment by BlueNalgene** [comment]
Correction for #1 made.  

Same exceptions pop up.  Verbose:class gives similar results as above.  The only difference is in the hex that shows up with LambdaForm bytecode dumps.

```
[Unloading class java.lang.invoke.LambdaForm$BMH/18707146 0xa45d6818]
[Unloading class java.lang.invoke.LambdaForm$BMH/21122690 0xa45d5e18]
[Unloading class java.lang.invoke.LambdaForm$BMH/24137948 0xa45d4a18]
[Unloading class java.lang.invoke.LambdaForm$BMH/15096457 0xa45c7018]
[Unloading class java.lang.invoke.LambdaForm$BMH/33078119 0xa45b3018]

```

**Comment by dominiks** [comment]
Do you know how large the generated world is you are trying to map? Unfortunately I cannot reproduce the issue at the moment. How much memory does the host have?

You could also try to increase the heap size by starting with `-Xmx1024M` (or more).

I'll have a look at the code in your trace and see if I can find anything.

**Comment by BlueNalgene** [comment]
The host machine is an old laptop which is now running as a home server.  It is running headless (terminal only, no display drivers) Ubuntu.  The computer has:

```
/0/a                        memory      1536MiB System Memory
/0/a/0                      memory      1GiB SODIMM DDR2
/0/a/1                      memory      512MiB SODIMM DDR2
```

The DF world was generated with the following parameters included:

```
[DIM:257:257]
[EMBARK_POINTS:1504]
[END_YEAR:1050]
[TOTAL_CIV_POPULATION:15000]
[SITE_CAP:1500]
```

So this is what I would consider a normal sized map for what I usually make to run with DF games.  There is no problem running Uristmaps on my beefier Windows unit (32Gb memory, high end processor, etc.).  The map was produced on that machine.  I would host it on that machine, but I have plans for doing something experimental on the linux server.

Running the jar file with 1024Mb heap seems to be successful.  This is the edited debug output:

```
00:00  INFO: Uristmaps 0.3.3
00:00  INFO: Enabled Debug Logging
00:01  INFO: Starting full build
00:01 DEBUG: [TaskExecutor] Starting: BmpConvertTask
00:01 DEBUG: [BmpConverter] Started
00:01 DEBUG: [TaskExecutor] Completed: BmpConvertTask
00:01 DEBUG: [TaskExecutor] Starting: DistResources
00:01  INFO: [FileCopier] Copying static resources to output.
00:01 DEBUG: [TaskExecutor] Completed: DistResources
00:01 DEBUG: [TaskExecutor] Starting: GroupStructures
00:01 DEBUG: [StructureGroups] Reading groupMap from exported files.
00:02 DEBUG: [StructureInfo] Loading
00:16 DEBUG: [StructureInfo] Done
00:28 DEBUG: [TaskExecutor] Completed: GroupStructures
00:28 DEBUG: [TaskExecutor] Starting: Sites
00:28  INFO: [Sites] Loading site information
00:28 DEBUG: [LegendsParser] Starting document
01:08 DEBUG: [LegendsParser] Finished Document
01:08  WARN: [SiteCenters] Could not find close group for site Smaspestnako(Dark Pits)@2920,3672
01:08  WARN: [SiteCenters] Could not find close group for site Mogshumducim(Hillocks)@536,3192
01:08  WARN: [SiteCenters] Could not find close group for site Letmosstizash(Hillocks)@1960,904
01:08  WARN: [SiteCenters] Could not find close group for site Slagbosa(Dark Pits)@2472,232
01:08  WARN: [SiteCenters] Could not find close group for site Omosp�sbu(Dark Pits)@920,2760
01:08  WARN: [SiteCenters] Could not find close group for site Stosloolng�(Dark Pits)@2520,200
01:08  WARN: [SiteCenters] Could not find close group for site Ungn�ngoso(Dark Pits)@2744,3560
01:08  WARN: [SiteCenters] Could not find close group for site Rimtartathur(Hillocks)@1448,3656
01:08  WARN: [SiteCenters] Could not find close group for site Nobdeogur(Dark Pits)@2600,280
01:08  WARN: [SiteCenters] Could not find close group for site Ngerxungzok(Dark Pits)@3592,600
01:08  WARN: [SiteCenters] Could not find close group for site �spsnang(Dark Pits)@2616,200
01:08  WARN: [SiteCenters] Could not find close group for site Udastutes(Dark Pits)@3544,1464
01:08  WARN: [SiteCenters] Could not find close group for site Ngureolng�(Dark Pits)@2600,296
01:08  WARN: [SiteCenters] Could not find close group for site Aglob�x(Dark Pits)@3528,1096
01:08  WARN: [SiteCenters] Could not find close group for site Rutmato(Dark Pits)@3464,1112
01:08  WARN: [SiteCenters] Could not find close group for site Atungokang(Dark Pits)@2776,3416
01:08  WARN: [SiteCenters] Could not find close group for site Ureddang(Dark Pits)@2776,3400
01:08  WARN: [SiteCenters] Could not find close group for site Odatarifa(Forest Retreat)@3416,2968
01:08  WARN: [SiteCenters] Could not find close group for site Turstosb�b(Dark Pits)@2616,296
01:08  WARN: [SiteCenters] Could not find close group for site Olinedos(Hillocks)@2200,888
01:08  WARN: [SiteCenters] Could not find close group for site Aslotng�rdax(Dark Pits)@3544,1432
01:08 DEBUG: [Sites] Writing site info
01:08 DEBUG: [TaskExecutor] Completed: Sites
01:08 DEBUG: [TaskExecutor] Starting: CompileIndex
01:08  INFO: [TemplateRenderer] Writing index.html
01:09 DEBUG: [TaskExecutor] Completed: CompileIndex
01:09 DEBUG: [TaskExecutor] Starting: CopySiteMaps
01:09 DEBUG: [TaskExecutor] Completed: CopySiteMaps
01:09 DEBUG: [TaskExecutor] Starting: TilesetTask:16
01:09  INFO: [Tileset] Compiling tileset in /home/nginx/uristmaps/tiles/16
01:10 DEBUG: [FileWatcher] Updated 144 files.
01:10 DEBUG: [FileWatcher] Saved store.
01:10 DEBUG: [TaskExecutor] Completed: TilesetTask:16
01:10 DEBUG: [TaskExecutor] Starting: TilesetTask:4
01:10  INFO: [Tileset] Compiling tileset in /home/nginx/uristmaps/tiles/4
01:11 DEBUG: [FileWatcher] Updated 144 files.
01:11 DEBUG: [FileWatcher] Saved store.
01:11 DEBUG: [TaskExecutor] Completed: TilesetTask:4
01:11 DEBUG: [TaskExecutor] Starting: TilesetTask:64
01:11  INFO: [Tileset] Compiling tileset in /home/nginx/uristmaps/tiles/64
01:11 DEBUG: [FileWatcher] Updated 94 files.
01:11 DEBUG: [FileWatcher] Saved store.
01:11 DEBUG: [TaskExecutor] Completed: TilesetTask:64
01:11 DEBUG: [TaskExecutor] Starting: TilesetTask:8
01:11  INFO: [Tileset] Compiling tileset in /home/nginx/uristmaps/tiles/8
01:11 DEBUG: [FileWatcher] Updated 144 files.
01:11 DEBUG: [FileWatcher] Saved store.
01:11 DEBUG: [TaskExecutor] Completed: TilesetTask:8
01:11 DEBUG: [TaskExecutor] Starting: TilesetTask:32
01:11  INFO: [Tileset] Compiling tileset in /home/nginx/uristmaps/tiles/32
01:11 DEBUG: [FileWatcher] Updated 144 files.
01:11 DEBUG: [FileWatcher] Saved store.
01:12 DEBUG: [TaskExecutor] Completed: TilesetTask:32
01:12 DEBUG: [TaskExecutor] Starting: TilesetTask:1
01:12 DEBUG: [TaskExecutor] Completed: TilesetTask:1
01:12 DEBUG: [TaskExecutor] Starting: TilesetTask:2
01:12 DEBUG: [TaskExecutor] Completed: TilesetTask:2
01:12 DEBUG: [TaskExecutor] Starting: PopulationHeatmaps
01:12  INFO: [Heatmaps] Writing population info
01:12 DEBUG: [TaskExecutor] Completed: PopulationHeatmaps
01:12 DEBUG: [TaskExecutor] Starting: CompileUristJs
01:12  INFO: [TemplateRenderer] Writing urist.js
01:12 DEBUG: [TaskExecutor] Completed: CompileUristJs
01:12 DEBUG: [TaskExecutor] Starting: LoadSitemaps
01:12 DEBUG: [TaskExecutor] Completed: LoadSitemaps
01:12 DEBUG: [TaskExecutor] Starting: SitesGeojson
01:13 DEBUG: [TaskExecutor] Completed: SitesGeojson
01:13 DEBUG: [TaskExecutor] Starting: BiomeRenderer:0
02:07  INFO: [SatRenderer] Rendering zoom level 0 using 1px sized graphics (1 cols).
02:07 DEBUG: [SatRenderer] Creating thread pool with size 2
02:07 DEBUG: [SatRenderer] Waiting for pool to shutdown.
02:07  INFO: [SatRenderer] 100% (1/1)
02:07 DEBUG: [TaskExecutor] Completed: BiomeRenderer:0
02:07 DEBUG: [TaskExecutor] Starting: BiomeRenderer:1
02:07  INFO: [SatRenderer] Rendering zoom level 1 using 1px sized graphics (2 cols).
02:07 DEBUG: [SatRenderer] Creating thread pool with size 2
02:07 DEBUG: [SatRenderer] Waiting for pool to shutdown.
02:07  INFO: [SatRenderer] 50% (1/2)
02:07  INFO: [SatRenderer] 100% (2/2)
02:07 DEBUG: [TaskExecutor] Completed: BiomeRenderer:1
02:07 DEBUG: [TaskExecutor] Starting: BiomeRenderer:2
02:07  INFO: [SatRenderer] Rendering zoom level 2 using 1px sized graphics (4 cols).
02:07 DEBUG: [SatRenderer] Creating thread pool with size 2
02:07 DEBUG: [SatRenderer] Waiting for pool to shutdown.
02:07  INFO: [SatRenderer] 25% (1/4)
sic
02:07  INFO: [SatRenderer] 100% (4/4)
02:07 DEBUG: [TaskExecutor] Completed: BiomeRenderer:2
02:07 DEBUG: [TaskExecutor] Starting: BiomeRenderer:3
02:07  INFO: [SatRenderer] Rendering zoom level 3 using 1px sized graphics (8 cols).
02:07 DEBUG: [SatRenderer] Creating thread pool with size 2
02:07 DEBUG: [SatRenderer] Waiting for pool to shutdown.
02:08  INFO: [SatRenderer] 12% (1/8)
sic
02:10  INFO: [SatRenderer] 100% (8/8)
02:10 DEBUG: [TaskExecutor] Completed: BiomeRenderer:3
02:10 DEBUG: [TaskExecutor] Starting: BiomeRenderer:4
02:10  INFO: [SatRenderer] Rendering zoom level 4 using 1px sized graphics (16 cols).
02:10 DEBUG: [SatRenderer] Creating thread pool with size 2
02:10 DEBUG: [SatRenderer] Waiting for pool to shutdown.
02:10  INFO: [SatRenderer] 6% (1/16)
sic
02:17  INFO: [SatRenderer] 100% (16/16)
02:17 DEBUG: [TaskExecutor] Completed: BiomeRenderer:4
02:17 DEBUG: [TaskExecutor] Starting: BiomeRenderer:5
02:17  INFO: [SatRenderer] Rendering zoom level 5 using 1px sized graphics (32 cols).
02:17 DEBUG: [SatRenderer] Creating thread pool with size 2
02:17 DEBUG: [SatRenderer] Waiting for pool to shutdown.
02:18  INFO: [SatRenderer] 3% (1/32)
sic
02:43  INFO: [SatRenderer] 93% (30/32)
02:43 DEBUG: [TaskExecutor] Completed: BiomeRenderer:5
02:43 DEBUG: [TaskExecutor] Starting: BiomeRenderer:6
02:43  INFO: [SatRenderer] Rendering zoom level 6 using 2px sized graphics (64 cols).
02:43 DEBUG: [SatRenderer] Creating thread pool with size 2
02:43 DEBUG: [SatRenderer] Waiting for pool to shutdown.
02:44  INFO: [SatRenderer] 1% (1/64)
sic
03:39  INFO: [SatRenderer] 100% (64/64)
03:39 DEBUG: [TaskExecutor] Completed: BiomeRenderer:6
03:39 DEBUG: [TaskExecutor] Starting: BiomeRenderer:7
03:39  INFO: [SatRenderer] Rendering zoom level 7 using 4px sized graphics (128 cols).
03:39 DEBUG: [SatRenderer] Creating thread pool with size 2
03:39 DEBUG: [SatRenderer] Waiting for pool to shutdown.
03:41  INFO: [SatRenderer] 0% (1/128)
sic
10:02  INFO: [SatRenderer] 100% (128/128)
10:02 DEBUG: [TaskExecutor] Completed: BiomeRenderer:7
10:03 DEBUG: [TaskExecutor] Starting: BiomeRenderer:8
10:03  INFO: [SatRenderer] Rendering zoom level 8 using 8px sized graphics (256 cols).
10:03 DEBUG: [SatRenderer] Creating thread pool with size 2
10:03 DEBUG: [SatRenderer] Waiting for pool to shutdown.
10:07  INFO: [SatRenderer] 0% (1/256)
sic
24:09  INFO: [SatRenderer] 100% (256/256)
24:09 DEBUG: [TaskExecutor] Completed: BiomeRenderer:8
24:09 DEBUG: [TaskExecutor] Skipped: FullBuild
24:09 DEBUG: [FileWatcher] Updated 683 files.
24:09 DEBUG: [FileWatcher] Saved store.

```

By adding `-Xmx1024M` to the uristmaps.sh file, the host runs successfully.  Thanks

**Comment by dominiks** [comment]
Glad to hear it's working for you now. I'll add this as a possible solution to the readme for others who might encounter a OutOfMemoryError exception.

It still is, of course, a problem that the program crashes in such a way on a low memory machine and I'll keep it in mind to lower the memory usage.

And thank you for helping me improve uristmaps!
