### ISSUE TITLE
NullPointerException crash on startup

### ISSUE THREAD

**Issue by alexchandel** [dominiks/uristmapsj#6]
Seems like it's caused by getDate() in getLegendsXML().

```
00:00  INFO: Uristmaps 0.3.3
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:342)
	at com.simontuffs.onejar.Boot.main(Boot.java:168)
Caused by: java.lang.NullPointerException
	at org.uristmaps.util.ExportFiles.getDate(ExportFiles.java:48)
	at org.uristmaps.util.ExportFiles.getLegendsXML(ExportFiles.java:70)
	at org.uristmaps.Uristmaps.main(Uristmaps.java:81)
	... 6 more
```

**Comment by 7ff04da4aa6ac37197e249299066ac30** [comment]
You ever got this to work? Facing this right now

EDIT: nevermind, it was just a formatting error on my part (though I _do_ think it's stupid). On the "export" line in the config.cfg, I passed the path as "foo/bar" instead of "foo/bar/". Reporting this here in case someone else comes across this problem.
